steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-python-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gunicorn'
    args:
      - 'run'
      - 'deploy'
      - 'my-python-app'
      - '--image=gcr.io/$PROJECT_ID/my-python-app'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--timeout=600s'
      - '--port=8080'
      - '--set-env-vars=PORT=8080'
      - '--cpu=1'
      - '--memory=1Gi'
options:
  logging: CLOUD_LOGGING_ONLY
